erp:
    banmaerp:
        X_BANMA_APP_NAME: 选品中心
        X_BANMA_MASTER_APP_ACCOUNT: 15060715230
        X_BANMA_MASTER_APP_ID: 1492055167686688768
        X_BANMA_MASTER_APP_SECRET: a7437ad68d0f457b9788e17f92e13b0f
        X_BANMA_MASTER_SIGN_ALGORITHM: SHA256
        X_BANMA_MASTER_SIGN_METHOD: IP白名单
        enabled: true
        tasks:
            sync:
#                cron: 0 0/30 * * * ? #for test only
                cron:  0 0 0/1 * * ?
                delayInMs: 1000
                enabled: true
h2server:
    enabled: false
    port: 7777
msg:
    webhook:
        dingtalk:
            access_token: 5502e6e4abdcce21a8d3ae71614c7708421b45f32ad33344a713d6638207e7d7
            enable: true
            url: https://oapi.dingtalk.com/robot/send?access_token=5502e6e4abdcce21a8d3ae71614c7708421b45f32ad33344a713d6638207e7d7
        qywechat:
            enable: true
            key: a34d8f1c-a22d-4d2c-aeea-5323d7ae35d2
            url: https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=a34d8f1c-a22d-4d2c-aeea-5323d7ae35d2


spring:
    # for test only
#    profiles:
#        active: devbanmaerp
    # test end
    datasource:
        banmaerp:
            url: jdbc:mysql://${spring.datasource.banmaerp.host}:${spring.datasource.banmaerp.port}/banmaerp?characterEncoding=utf8&autoReconnect=true&useUnicode=true&tcpKeepAlive=true&useSSL=false&allowPublicKeyRetrieval=true&useLegacyDateTimeCode=false&serverTimezone=Asia/Shanghai&
            druid:
                connection-error-retry-attempts: 3 # 3
                connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=30000
                initial-size: 30
                keep-alive: true
                keep-alive-between-time-millis: 120000
                maxActive: 600
                maxPoolPreparedStatementPerConnectionSize: 20
                maxWait: 60000
                min-idle: 30
                minEvictableIdleTimeMillis: 300000 #300000
                maxEvictableIdleTimeMillis: 7200000 #set to 1Hr, default 7Hrs, mysql 8Hrs
                password: ${spring.datasource.banmaerp.password}
                poolPreparedStatements: true
                testOnBorrow: false
                testOnReturn: false
                testWhileIdle: true #建议开启 keepAlive 参数用于对空闲连接做有效性检测。Druid 中 testWhileIdle 和普通的连接池（DBCP 等）所表达的含义并不相同，使用时候需要慎重
                timeBetweenEvictionRunsMillis: 90000 #60000
                url: ${spring.datasource.banmaerp.url}
                username: ${spring.datasource.banmaerp.username}
                validationQuery: SELECT 1
                validation-query: SELECT 1
            hikari:
                connection-timeout: 10000
                idle-timeout: 600000
                jdbc-url: ${spring.datasource.banmaerp.url}
                keepaliveTime: 60000
                max-lifetime: 21600000
                maximum-pool-size: 20
                minimum-idle: 5
    data:
        redis:
            repositories:
                enabled: false
