erp:
    banmaerp:
        X_BANMA_APP_NAME: 选品中心
        X_BANMA_MASTER_APP_ACCOUNT: 15060715230
        X_BANMA_MASTER_APP_ID: 1492055167686688768
        X_BANMA_MASTER_APP_SECRET: a7437ad68d0f457b9788e17f92e13b0f
        X_BANMA_MASTER_SIGN_ALGORITHM: SHA256
        X_BANMA_MASTER_SIGN_METHOD: IP白名单
        enabled: true
        tasks:
            sync:
#                cron: 0 0/10 * * * ? #for test only
                cron:  0 0 0/1 * * ?
                delayInMs: 10000
                enabled: true
h2server:
    enabled: false
    port: 7777

msg:
    webhook:
        dingtalk:
            access_token: 5502e6e4abdcce21a8d3ae71614c7708421b45f32ad33344a713d6638207e7d7
            enable: true
            url: https://oapi.dingtalk.com/robot/send?access_token=5502e6e4abdcce21a8d3ae71614c7708421b45f32ad33344a713d6638207e7d7
        qywechat:
            enable: true
            key: a34d8f1c-a22d-4d2c-aeea-5323d7ae35d2
            url: https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=a34d8f1c-a22d-4d2c-aeea-5323d7ae35d2


spring:
    datasource:
        banmaerp:
            druid:
                connection-error-retry-attempts: 3
                connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
                initial-size: 3
                keep-alive: true
                keep-alive-between-time-millis: 60000
                maxActive: 600
                maxPoolPreparedStatementPerConnectionSize: 20
                maxWait: 60000
                min-idle: 10
                minEvictableIdleTimeMillis: 300000
                password: ${spring.datasource.banmaerp.password}
                poolPreparedStatements: true
                testOnBorrow: false
                testOnReturn: false
                testWhileIdle: true
                timeBetweenEvictionRunsMillis: 30000
                url: ${spring.datasource.banmaerp.url}
                username: ${spring.datasource.banmaerp.username}
                validationQuery: SELECT 1 FROM DUAL
            hikari:
                connection-timeout: 10000
                idle-timeout: 600000
                jdbc-url: ${spring.datasource.banmaerp.url}
                keepaliveTime: 60000
                max-lifetime: 21600000
                maximum-pool-size: 20
                minimum-idle: 5
            password: ${spring.datasource.password}
            url: jdbc:mysql://${spring.datasource.host}:${spring.datasource.port}/banmaerp?characterEncoding=utf8&autoReconnect=true&useUnicode=true&tcpKeepAlive=true&useSSL=false&allowPublicKeyRetrieval=true&useLegacyDateTimeCode=false&serverTimezone=Asia/Shanghai&
            username: ${spring.datasource.username}

