spring:
  redis:
    host: rds.xmsuodi.com
    port: 46379
    password: lilishop
    database: 1
    #    cluster:
    #      nodes:
    lettuce:
      pool:
        max-wait: 1000
        max-idle: 20
        min-idle: 10
        max-active: 2000
  datasource:
    banmaerp:
      username: root
      password: lilishop
      url: jdbc:mysql://rds.xmsuodi.com:49906/banmaerp_ljl?characterEncoding=utf8&autoReconnect=true&useUnicode=true&tcpKeepAlive=true&useSSL=false&allowPublicKeyRetrieval=true&useLegacyDateTimeCode=false&serverTimezone=Asia/Shanghai&
      druid:
        username: ${spring.datasource.banmaerp.username}
        password: ${spring.datasource.banmaerp.password}
        url: ${spring.datasource.banmaerp.url}
        initial-size: 10
        min-idle: 10
        maxActive: 600
        maxWait: 60000
        timeBetweenEvictionRunsMillis: 30000
        minEvictableIdleTimeMillis: 300000
        validationQuery: SELECT 1 FROM DUAL
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxPoolPreparedStatementPerConnectionSize: 20
        connection-error-retry-attempts: 3
        keep-alive: true
        keep-alive-between-time-millis: 60000
        connectionProperties: druid.stat.mergeSql\=true;druid.stat.slowSqlMillis\=5000

      hikari:
        maximum-pool-size: 20
        max-lifetime: 21600000
        minimum-idle: 5
        idle-timeout: 600000
        connection-timeout: 10000
        keepaliveTime: 60000
        jdbc-url: ${spring.datasource.banmaerp.url}
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
      ddl-auto: create
    generate-ddl: true
    show-sql: true

actable:
  table:
    auto: update
  model:
    pack: com.hrghs.xycb
  database:
    type: mysql
