spring:
  datasource:
    banmaerp:
            # for test only
      host: 192.168.18.151
      port: 3306
#            host: rds.xmsuodi.com
#      host: 120.41.238.146
#      port: 49906
      password: lilishop
      username: root
            # test end
  redis:
    port: 6379
    host: 192.168.18.151
#    port: 46379
#    host: 120.41.238.146
#        host: rds.xmsuodi.com
#        port: 6379
#        host: 127.0.0.1
    database: 3
    password: lilishop
