spring:
    datasource:
        banmaerp:
            # for test only
            host: 192.168.18.151
            port: 3306
            password: lilishop
            username: root
            # test end
    redis:
        port: 6379
        host: 192.168.18.151
        database: 4
        password: lilishop

